name = "ai-powered-static-portfolio-worker"
compatibility_date = "2025-09-15"

[assets]
binding = "ASSETS"
directory = "./frontend/dist"
not_found_handling = "single-page-application"

[dev]
inspector_port = 0
